### ISSUE TITLE
java.lang.NoClassDefFoundError: sbt/JettyConfiguration 

### ISSUE THREAD

**Issue by nafg** [scalastuff/esbt#7]
When running SBT Update Dependencies I get:

------ Processing project:  ------
[info] Compiling 2 Scala sources to /home/naftoli/.sbt/plugins/project/target/scala_2.8.1/classes...
[info] Set current project to root (in build file:/home/naftoli/.sbt/plugins/)
[info] Updating...
[info] Updating...
[info] Done updating.
[info] Compiling 1 Scala source to /home/naftoli/.sbt/staging/1375c2d4ab8153e18523/target/scala-2.8.1.final/classes...
[info] Done updating.
java.lang.NoClassDefFoundError: sbt/JettyConfiguration
    at com.github.siasia.WebPlugin$.<init>(WebPlugin.scala:27)
    at com.github.siasia.WebPlugin$.<clinit>(WebPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
    at sbt.Load$.loadPlugin(Load.scala:393)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:390)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:390)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:196)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:196)
    at scala.collection.immutable.Stream.append(Stream.scala:81)
    at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:81)
    at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:81)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:565)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:557)
    at scala.collection.immutable.Stream.filter(Stream.scala:210)
    at scala.collection.immutable.Stream.filter(Stream.scala:48)
    at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:250)
    at scala.collection.immutable.Stream.filterNot(Stream.scala:48)
    at scala.collection.immutable.Stream.partition(Stream.scala:280)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:136)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:133)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
    at scala.collection.immutable.List.flatMap(List.scala:45)
    at sbt.Load$.buildConfigurations(Load.scala:133)
    at sbt.Load$.apply(Load.scala:86)
    at sbt.Load$.buildPluginDefinition(Load.scala:345)
    at sbt.Load$.buildPlugins(Load.scala:335)
    at sbt.Load$.plugins(Load.scala:332)
    at sbt.Load$.loadUnit(Load.scala:318)
    at sbt.Load$$anonfun$5.apply(Load.scala:172)
    at sbt.Load$$anonfun$5.apply(Load.scala:172)
    at sbt.BuildLoader.apply(BuildLoader.scala:17)
    at sbt.Load$.loadAll(Load.scala:224)
    at sbt.Load$.loadURI(Load.scala:181)
    at sbt.Load$.load(Load.scala:177)
    at sbt.Load$.load(Load.scala:175)
    at sbt.Load$.apply(Load.scala:83)
    at sbt.Load$.defaultLoad(Load.scala:41)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:371)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:368)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$.process(Command.scala:91)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
    at sbt.State$$anon$1.process(State.scala:54)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
    at sbt.MainLoop$.next(Main.scala:72)
    at sbt.MainLoop$.run(Main.scala:63)
    at sbt.xMain.run(Main.scala:33)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.JettyConfiguration
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at com.github.siasia.WebPlugin$.<init>(WebPlugin.scala:27)
    at com.github.siasia.WebPlugin$.<clinit>(WebPlugin.scala)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:10)
    at sbt.Load$.loadPlugin(Load.scala:393)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:390)
    at sbt.Load$$anonfun$loadPlugins$1.apply(Load.scala:390)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:196)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:196)
    at scala.collection.immutable.Stream.append(Stream.scala:81)
    at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:81)
    at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:81)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:565)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:557)
    at scala.collection.immutable.Stream.filter(Stream.scala:210)
    at scala.collection.immutable.Stream.filter(Stream.scala:48)
    at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:250)
    at scala.collection.immutable.Stream.filterNot(Stream.scala:48)
    at scala.collection.immutable.Stream.partition(Stream.scala:280)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:136)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:133)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
    at scala.collection.immutable.List.flatMap(List.scala:45)
    at sbt.Load$.buildConfigurations(Load.scala:133)
    at sbt.Load$.apply(Load.scala:86)
    at sbt.Load$.buildPluginDefinition(Load.scala:345)
    at sbt.Load$.buildPlugins(Load.scala:335)
    at sbt.Load$.plugins(Load.scala:332)
    at sbt.Load$.loadUnit(Load.scala:318)
    at sbt.Load$$anonfun$5.apply(Load.scala:172)
    at sbt.Load$$anonfun$5.apply(Load.scala:172)
    at sbt.BuildLoader.apply(BuildLoader.scala:17)
    at sbt.Load$.loadAll(Load.scala:224)
    at sbt.Load$.loadURI(Load.scala:181)
    at sbt.Load$.load(Load.scala:177)
    at sbt.Load$.load(Load.scala:175)
    at sbt.Load$.apply(Load.scala:83)
    at sbt.Load$.defaultLoad(Load.scala:41)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:371)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:368)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$.process(Command.scala:91)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:72)
    at sbt.State$$anon$1.process(State.scala:54)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:72)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
    at sbt.MainLoop$.next(Main.scala:72)
    at sbt.MainLoop$.run(Main.scala:63)
    at sbt.xMain.run(Main.scala:33)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: sbt/JettyConfiguration
[error] Use 'last' for the full log.
----- Done (75006 ms)------

Any idea?

**Comment by nafg** [comment]
Don't think I've had this recently, so if you want you can close it.
